Unable to init server: Could not connect: Connection refused
Unable to init server: Impossible de se connecterÂ : Connection refused

(model.py:17214): Gdk-CRITICAL **: 23:21:09.725: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
slurmstepd: error: *** JOB 7279 ON sh04 CANCELLED AT 2022-01-31T23:55:52 ***
